### PR TITLE
159 bug tauri open function not opening log and data directories

### LINKED ISSUE #159: [BUG] Tauri open function not opening Log and Data directories

### PR DESCRIPTION
**Pull request by quexeky**

### CODE REVIEW

File: src-tauri/src/client.rs [hunk 1]
```diff
@@ -72,3 +73,10 @@ pub fn get_autostart_enabled(app: AppHandle) -> Result<bool, tauri_plugin_autost
 
     Ok(db_state)
 }
+
+#[tauri::command]
+pub fn open_fs(path: String, app_handle: AppHandle) -> Result<(), tauri_plugin_opener::Error> {
+    app_handle
+        .opener()
+        .open_path(path, None::<&str>)
```
Comment (DecDuck) [inline src-tauri/src/client.rs:81]: What's the second argument here?
